openapi: 3.0.3
info:
  title: Reproducer
  version: V1.0
paths:
  /foobar:
    get:
      operationId: getFoo
      x-vertx-event-bus:
        address: "fooService"
      parameters:
        - name: foo
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/foobar'
            example: '[{"foo": "bar"},{"foo" : "bar"}]'
      responses:
        '200':
          description: The response
components:
  schemas:
    foobar:
      allOf:
      - type: object
        required:
        - foo
        properties:
          foo:
            type: string
